# -*- coding: utf-8 -*-
"""Untitled128.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10thU2hmQIiUsAJQlgyvJ1FdhsLNB5pYq
"""

from PIL import Image
import matplotlib.pyplot as plt

def read_image_from_path(image_path):
  """Reads an image from the specified path using Pillow library.

  Args:
    image_path: The path to the image file.

  Returns:
    A PIL Image object if the image is read successfully,
    otherwise None.
  """
  try:
    img = Image.open(image_path)
    return img
  except FileNotFoundError:
    print(f"Error: Image file not found at {image_path}")
    return None
  except Exception as e:
    print(f"Error reading image: {e}")
    return None

# Example usage
image_path = '/content/logo_transparent.png'  # Replace with your image path
image = read_image_from_path(image_path)

if image:
  # Display the image (optional)
  plt.imshow(image)
  plt.axis('off')  # Hide axis
  plt.show()

  # Access image properties (optional)
  print(f"Image format: {image.format}")
  print(f"Image mode: {image.mode}")
  print(f"Image size: {image.size}")

